import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import './globals.css'

const nunitoSans = Nunito_Sans({
	variable: '--font-nunito-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Age Of Traders',
	description: 'Generated by create next app',
	// Indexing is temporarily disabled
	robots: {
		index: false,
		follow: false,
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${nunitoSans.variable} antialiased`}>{children}</body>
		</html>
	)
}
